/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tw.fp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MoneyAppTest {
    @Test void appHasAGreeting() {
        MoneyApp classUnderTest = new MoneyApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
