/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tw.fp;

public class MoneyApp {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new MoneyApp().getGreeting());
    }
}
